### ISSUE TITLE
I start testing lda-ruby gem. But for topic, it set default 20. How can I can change that one? I would like to test different topic number. 

### ISSUE THREAD

**Issue by khinezarthwe** [ealdent/lda-ruby#12]

**Comment by ealdent** [comment]
You should be able to set num_topics on the lda instance to the number of topics you wish to use.  So let's say `lda` is an instance you created with `Lda::Lda.new`, then

```
lda.num_topics = 5
lda.em("random")
```

Please re-open this issue if that doesn't work.

Thanks!

**Comment by khinezarthwe** [comment]
Yes, thanks. Now it is work.
