### ISSUE TITLE
Infer topic distribution for new document

### ISSUE THREAD

**Issue by jasmarc** [ealdent/lda-ruby#3]
So, my research project partner and I were wondering "can it infer the topic distribution of new (unseen) documents?"

If that's not a current feature, do you think it would be difficult to add? Maybe it's something I can help with.

Thanks,
Jason

**Comment by tricepa** [comment]
I'm playing around with this wrapper on some data and am interested in testing the model. Was this issue ever resolved?

**Comment by ealdent** [comment]
@tricepa no I guess I didn't have the chance to look at it at the time and I had forgotten about it entirely until just now.  If you happen to implement it and want me to merge in any code though, I'd be happy to, but I don't have the bandwidth to take this on myself right now.
